#!/usr/bin/env bash
#================================================================
# HEADER
#================================================================
#% SYNOPSIS
#+   ${SCRIPT_NAME} [-hvf] 
#%
#% DESCRIPTION
#%   This script updates setups up the Nexus image. It will erase most current settings
#%   if they exist
#%
#% OPTIONS
#%    -h, --help              Print this help
#%    -v, --version           Print script information
#%    -f, --force             Run script without printing warning message.
#% 
#% COMMANDS 
#%    APP(s)                  Zero or more applications (comma separated) to install,
#%                            or udpate if already installed.
#%                            If no APPs are supplied, the script runs in GUI
#%                            mode and presents a user interface in which the user
#%                            can select one or more APPs for installation or
#%                            upgrade.
#%                                
#% EXAMPLES
#%    Run the script in GUI mode and run the self-checker:
#%
#%      ${SCRIPT_NAME} -s
#%
#%    Run the script from the command line and install or update fldigi and flmsg:
#%
#%      ${SCRIPT_NAME} fldigi,flmsg  
#%    
#%    Run the script from the command line and force a reinstall of fldigi and flmsg:
#%
#%      ${SCRIPT_NAME} -f fldigi,flmsg  
#%    
#================================================================
#- IMPLEMENTATION
#-    version         ${SCRIPT_NAME} 2.1.3
#-    author          Steve Magnuson, AG7GN
#-    license         CC-BY-SA Creative Commons License
#-    script_id       0
#-
#================================================================
#  HISTORY
#     20201120 : Steve Magnuson : Script creation
#     20210623 : Steve Magnuson : Added check to ensure running from X (GUI)
# 
#================================================================
#  DEBUG OPTION
#    set -n  # Uncomment to check your syntax, without execution.
#    set -x  # Uncomment to debug this shell script
#
#================================================================
# END_OF_HEADER
#================================================================

SYNTAX=false
DEBUG=false
Optnum=$#

#============================
#  FUNCTIONS
#============================

function TrapCleanup() {
  [[ -d "${TMPDIR}" ]] && rm -rf "${TMPDIR}/"
  exit 0
}


function SafeExit() {
  # Exit with arg1
  EXIT_CODE=${1:-0}
  # Delete temp files, if any
  [[ -d "${TMPDIR}" ]] && rm -rf "${TMPDIR}/"
  trap - INT TERM EXIT
  exit $EXIT_CODE
}


function ScriptInfo() { 
	HEAD_FILTER="^#-"
	[[ "$1" = "usage" ]] && HEAD_FILTER="^#+"
	[[ "$1" = "full" ]] && HEAD_FILTER="^#[%+]"
	[[ "$1" = "version" ]] && HEAD_FILTER="^#-"
	head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "${HEAD_FILTER}" | \
	sed -e "s/${HEAD_FILTER}//g" \
	    -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g" \
	    -e "s/\${SPEED}/${SPEED}/g" \
	    -e "s/\${DEFAULT_PORTSTRING}/${DEFAULT_PORTSTRING}/g"
}


function Usage() { 
	printf "Usage: "
	ScriptInfo usage
	SafeExit 0
}


function Die () {
	echo "${*}"
	SafeExit 1
}


function AptError () {
   echo
   echo
   echo
   echo >&2 "ERROR while running '$1'.  Exiting."
   echo
   echo
   echo
   SafeExit 1
}


function CheckInternet() {
	# Check for Internet connectivity
	if ! ping -q -w 1 -c 1 github.com > /dev/null 2>&1
	then
   	yad --center --title="$TITLE" --info --borders=30 \
      	 --text="<b>No Internet connection found.  Check your Internet connection \
and run this script again.</b>" --buttons-layout=center \
	       --button=Close:0
   SafeExit 1
fi

}


function LocalRepoUpdate() {

	# Checks if a local repository is set up and if not clones it. If there is a local
	# repo, then do a 'git pull' to see if there are updates. If no updates, return $FALSE 
	# otherwise return $TRUE.  
	#
	# arg1: Name of app to install/update
	# arg2: git URL for app
	
	UP_TO_DATE=$FALSE
	REQUEST="$1"
	URL="$2"
	GIT_DIR="$(echo ${URL##*/} | sed -e 's/\.git$//')"
	cd $SRC_DIR
	echo "============= $REQUEST install/update requested ========"
	# See if local git repository exists. Create it ('git clone') if not
	if ! [[ -s $SRC_DIR/$GIT_DIR/.git/HEAD ]]
	then
		git clone $URL || { echo >&2 "======= git clone $URL failed ========"; SafeExit 1; }
	else  # See if local repo is up to date
		cd $GIT_DIR
		if git pull | tee /dev/stderr | grep -q "^Already"
		then
			echo "============= $REQUEST up to date ============="
			UP_TO_DATE=$TRUE
		fi
	fi
	cd $SRC_DIR
	[[ $UP_TO_DATE == $FALSE ]] && return $TRUE || return $FALSE
}


function NexusLocalRepoUpdate() {

	# Checks if a local Nexus repository is set up and if not clones it. If there 
	# is a local repo, then do a 'git pull' to see if there are updates. If no updates,
	# return $FALSE 
	# otherwise return $TRUE.  If there are updates, look for shell script named 
	# 'nexus-install' in repo and run it if present and executable.
	#
	# arg1: Name of app to install/update
	# arg2: git URL for app
	
	if (LocalRepoUpdate "$1" "$2") || [[ $FORCE == $TRUE ]]
	then
		cd $SRC_DIR
   	if [[ -x ${2##*/}/nexus-install ]]
   	then
   		${2##*/}/nexus-install || Die "Failed to install/update $1"
   	  	echo "======== $1 installed/updated ========"
			cd $SRC_DIR
      	return $TRUE
		fi
		return $TRUE
	else		
		cd $SRC_DIR
		return $FALSE
	fi
}

function WaitFor() {

   # Waits for a timeout to expire or a file to exist, whichever occurs first.
   # If timer expires, returns $FALSE, otherwise returns $TRUE
   # arg1: Path to file to look for
   # arg2: (optional) Timeout in seconds. Default is 5

   FILE_="$1"
   local -i T=${2:-5}
   while [[ ! -f "$FILE_" ]] && (( $T > 0 ))
   do
      sleep 1
      ((T--))
   done
   (( $T == 0 )) && return $FALSE || return $TRUE
}

#============================
#  FILES AND VARIABLES
#============================

# Set Temp Directory
# -----------------------------------
# Create temp directory with three random numbers and the process ID
# in the name.  This directory is removed automatically at exit.
# -----------------------------------
TMPDIR="/tmp/${SCRIPT_NAME}.$RANDOM.$RANDOM.$RANDOM.$$"
(umask 077 && mkdir "${TMPDIR}") || {
  Die "Could not create temporary directory! Exiting."
}

  #== general variables ==#
SCRIPT_NAME="$(basename ${0})" # scriptname without path
SCRIPT_DIR="$( cd $(dirname "$0") && pwd )" # script directory
SCRIPT_FULLPATH="${SCRIPT_DIR}/${SCRIPT_NAME}"
SCRIPT_ID="$(ScriptInfo | grep script_id | tr -s ' ' | cut -d' ' -f3)"
SCRIPT_HEADSIZE=$(grep -sn "^# END_OF_HEADER" ${0} | head -1 | cut -f1 -d:)
VERSION="$(ScriptInfo version | grep version | tr -s ' ' | cut -d' ' -f 4)" 

GITHUB_URL="https://github.com"
NEXUS_UPDATER_GIT_URL="$GITHUB_URL/AG7GN/nexus-updater"
NEXUS_AUDIO_GIT_URL="$GITHUB_URL/AG7GN/nexus-audio"
REBOOT="NO"
declare -r TRUE=0
declare -r FALSE=1
SRC_DIR="/usr/local/src/nexus"
sudo mkdir -p $SRC_DIR
sudo chown -f -R $USER:$USER $SRC_DIR
sudo mkdir -p /usr/local/share/applications
TITLE="Nexus Initializer - version $VERSION"
RUN_IT=$FALSE

#============================
#  PARSE OPTIONS WITH GETOPTS
#============================

Optnum=$#
  
#== set short options ==#
SCRIPT_OPTS=':fhv-:'

#== set long options associated with short one ==#
typeset -A ARRAY_OPTS
ARRAY_OPTS=(
	[help]=h
	[version]=v
	[string]=s
	[port]=p
)

LONG_OPTS="^($(echo "${!ARRAY_OPTS[@]}" | tr ' ' '|'))="

# Parse options
while getopts ${SCRIPT_OPTS} OPTION
do
	# Translate long options to short
	if [[ "x$OPTION" == "x-" ]]
	then
		LONG_OPTION=$OPTARG
		LONG_OPTARG=$(echo $LONG_OPTION | egrep "$LONG_OPTS" | cut -d'=' -f2-)
		LONG_OPTIND=-1
		[[ "x$LONG_OPTARG" = "x" ]] && LONG_OPTIND=$OPTIND || LONG_OPTION=$(echo $OPTARG | cut -d'=' -f1)
		[[ $LONG_OPTIND -ne -1 ]] && eval LONG_OPTARG="\$$LONG_OPTIND"
		OPTION=${ARRAY_OPTS[$LONG_OPTION]}
		[[ "x$OPTION" = "x" ]] &&  OPTION="?" OPTARG="-$LONG_OPTION"
		
		if [[ $( echo "${SCRIPT_OPTS}" | grep -c "${OPTION}:" ) -eq 1 ]]; then
			if [[ "x${LONG_OPTARG}" = "x" ]] || [[ "${LONG_OPTARG}" = -* ]]; then 
				OPTION=":" OPTARG="-$LONG_OPTION"
			else
				OPTARG="$LONG_OPTARG";
				if [[ $LONG_OPTIND -ne -1 ]]; then
					[[ $OPTIND -le $Optnum ]] && OPTIND=$(( $OPTIND+1 ))
					shift $OPTIND
					OPTIND=1
				fi
			fi
		fi
	fi

	# Options followed by another option instead of argument
	if [[ "x${OPTION}" != "x:" ]] && [[ "x${OPTION}" != "x?" ]] && [[ "${OPTARG}" = -* ]]
	then 
		OPTARG="$OPTION" OPTION=":"
	fi

	# Finally, manage options
	case "$OPTION" in
		h) 
			ScriptInfo full
			SafeExit 0
			;;
		v) 
			ScriptInfo version
			SafeExit 0
			;;
		f) 
			RUN_IT=$TRUE
			;;
		:) 
			Die "${SCRIPT_NAME}: -$OPTARG: option requires an argument"
			;;
		?) 
			Die "${SCRIPT_NAME}: -$OPTARG: unknown option"
			;;
	esac
done
shift $((${OPTIND} - 1)) ## shift options


#============================
#  MAIN SCRIPT
#============================

[ -z $DISPLAY ] && Die "${SCRIPT_NAME}: Must be run from lxterminal or xterm in a GUI, not via SSH or from the console."

if [[ $RUN_IT == $FALSE ]]
then
	echo >&2 "This script initializes a base Raspbian with Desktop OS, creating the Nexus"
	echo >&2 "image. If run with the -f option, it will overwrite MANY configuration"
	echo >&2 "settings, so use with care. "
	echo >&2
	echo >&2 "Run this script again with -f if you REALLY want to create a Nexus image."
	echo >&2
	SafeExit 0
fi

####### Real Time Clock #########
# Check for RTC dtoverlay
CONFIG_="/boot/config.txt"
echo >&2 "Adding RTC dtoverlay if needed..."
if ! grep -q "^dtoverlay=i2c-rtc,ds3231" $CONFIG_
then
	echo "# Enable ds3231 Real Time Clock (RTC)"  | sudo tee --append $CONFIG_ 1>/dev/null
	echo "dtoverlay=i2c-rtc,ds3231" | sudo tee --append $CONFIG_ 1>/dev/null
fi
echo >&2 "Done."

####### Install nexus-updater
NexusLocalRepoUpdate nexus-updater $NEXUS_UPDATER_GIT_URL
command -v nexus-updater.sh >/dev/null || Die "Nexus Updater installation failed."

####### AUDIO Setup ###########
####### Install nexus-audio
nexus-updater.sh nexus-audio $NEXUS_AUDIO_GIT_URL

####### Install fldigi, flmsg, flrig, direwolf, nexus-rmsgw
nexus-updater.sh fldigi,flmsg,flrig,flamp,direwolf

####### Install nexus-utilities and set up desktops
nexus-updater.sh nexus-utilities
for DESKTOP in /usr/local/share/applications/*.template
do
	sed -e "s/_LEFT_RADIO_/left radio/g" \
	 	-e "s/_RIGHT_RADIO_/right radio/g" \
		$DESKTOP | sudo tee ${DESKTOP%%.*}.desktop 1>/dev/null
done

####### Check Autostart 
# Check for presence of system LXDE-pi autostart and insert check-piano.sh if not 
# already present. nexus-utilities/nexus-install should take care of this, but checck
# anyway
echo >&2 "Adding check-piano.sh to autostart..."
AUTOSTART="/etc/xdg/lxsession/LXDE-pi/autostart"
if [[ -s $AUTOSTART ]] 
then
	if ! grep -q check-piano.sh $AUTOSTART 2>/dev/null
	then
		sudo sed -i '/@pcmanfm .*/a @bash \/usr\/local\/sbin\/check-piano.sh' $AUTOSTART
	fi
fi
echo >&2 "Done."

####### Set background
echo >&2 "Setting desktop background..."
mkdir -p $HOME/.config/pcmanfm/LXDE-pi
cp -f nexus-utilities/desktop-items-0.conf $HOME/.config/pcmanfm/LXDE-pi/
pcmanfm --reconfigure
echo >&2 "Done."

####### Install and enable the shutdown button service
echo >&2 "Setting up shutdown button service..."
sudo cp -f nexus-initialize/etc/systemd/system/shutdown_button.service /etc/systemd/system/
sudo systemctl enable shutdown_button.service
sudo systemctl start shutdown_button.service
echo >&2 "Done."

####### Set up crontab
WHO="$USER"
WHEN="@reboot"
WHAT="sleep 5 && /usr/local/sbin/initialize-pi.sh"
JOB="$WHEN $WHAT"
cat <(fgrep -i -v "$WHAT" <(sudo crontab -u $WHO -l)) <(echo "$JOB") | sudo crontab -u $WHO -

####### Install nexus-rmsgw
nexus-updater.sh nexus-rmsgw

####### Set up Fldigi to use PulseAudio with Fe-Pi sound card.
rm -rf $HOME/.nbems
rm -rf $HOME/.fltk

declare -A GPIO_STATE
GPIO_STATE[left]=8192
GPIO_STATE[right]=16

declare -A KISS_IO_PORT
KISS_IO_PORT[left]=7342
KISS_IO_PORT[right]=7344

declare -A KISS_OUT_PORT
KISS_OUT_PORT[left]=7343
KISS_OUT_PORT[right]=7345

declare -A ARQ_PORT
ARQ_PORT[left]=7322
ARQ_PORT[right]=7323

declare -A XML_PORT
XML_PORT[left]=7362
XML_PORT[right]=7363

declare -A FLRIG_PORT
FLRIG_PORT[left]=12345
FLRIG_PORT[right]=12346

declare -A XMLLOG_PORT
XMLLOG_PORT[left]=8421
XMLLOG_PORT[right]=8422

declare -A FLMSG_WEB_PORT
FLMSG_WEB_PORT[left]=8080
FLMSG_WEB_PORT[right]=8090

declare -A REVERSEAUDIO
REVERSEAUDIO[left]=0
REVERSEAUDIO[right]=1

for SIDE in left right
do

	# Fldigi
	echo >&2 "Initializing Fldigi $SIDE"
   rm -rf $HOME/.fldigi-$SIDE
   rm -rf $HOME/.nbems-$SIDE
   fldigi --config-dir $HOME/.fldigi-$SIDE --flmsg-dir $HOME/.nbems-$SIDE >/dev/null 2>&1 &
   PID_FLDIGI=$!
	sleep 2
   while pgrep fldigi >/dev/null 2>&1
   do
      WID=$(xdotool search --pid $PID_FLDIGI 2>/dev/null)
      [[ ! -z $WID ]] && xdotool windowclose $WID >/dev/null 2>&1
   done
   WaitFor $HOME/.fldigi-$SIDE/fldigi_def.xml || Die "$HOME/.fldigi-$SIDE/fldigi_def.xml never created."
   pkill -SIGTERM fldigi
   FLMSG_STRING="/usr/local/bin/flmsg --flmsg-dir /home/pi/.nbems-$SIDE --server-port ${FLMSG_WEB_PORT[$SIDE]} -title \"Flmsg ($SIDE radio)\""
	sed -i -e "s/<SIGONRIGHTCHANNEL>.*<\/SIGONRIGHTCHANNEL>/<SIGONRIGHTCHANNEL>0<\/SIGONRIGHTCHANNEL>/" \
   -e "s/<ALERTDEVICE>.*<\/ALERTDEVICE>/<ALERTDEVICE>system-audio-playback<\/ALERTDEVICE>/" \
   -e "s/<ALERTINDEX>.*<\/ALERTINDEX>/<ALERTINDEX>10<\/ALERTINDEX>/" \
	-e "s/<AUDIOIO>.*<\/AUDIOIO>/<AUDIOIO>2<\/AUDIOIO>/" \
	-e "s/<ENABLE_AUDIO_ALERTS>.*<\/ENABLE_AUDIO_ALERTS>/<ENABLE_AUDIO_ALERTS>0<\/ENABLE_AUDIO_ALERTS>/" \
   -e "s/<PORTINDEVICE>.*<\/PORTINDEVICE>/<PORTINDEVICE>pulse<\/PORTINDEVICE>/" \
   -e "s/<PORTININDEX>.*<\/PORTININDEX>/<PORTININDEX>-1<\/PORTININDEX>/" \
   -e "s/<PORTOUTDEVICE>.*<\/PORTOUTDEVICE>/<PORTOUTDEVICE><\/PORTOUTDEVICE>/" \
   -e "s/<PORTOUTINDEX>.*<\/PORTOUTINDEX>/<PORTOUTINDEX>-1<\/PORTOUTINDEX>/" \
   -e "s/<ENABLE_GPIO>.*<\/ENABLE_GPIO>/<ENABLE_GPIO>${GPIO_STATE[$SIDE]}<\/ENABLE_GPIO>/" \
   -e "s/<GPIO_STATE>.*<\/GPIO_STATE>/<GPIO_STATE>${GPIO_STATE[$SIDE]}<\/GPIO_STATE>/" \
   -e "s/<XMLRPC_PORT>.*<\/XMLRPC_PORT>/<XMLRPC_PORT>${XML_PORT[$SIDE]}<\/XMLRPC_PORT>/" \
-e "s/<KISS_IO_PORT>.*<\/KISS_IO_PORT>/<KISS_IO_PORT>${KISS_IO_PORT[$SIDE]}<\/KISS_IO_PORT>/" \
   -e "s/<KISS_OUT_PORT>.*<\/KISS_OUT_PORT>/<KISS_OUT_PORT>${KISS_OUT_PORT[$SIDE]}<\/KISS_OUT_PORT>/" \
   -e "s/<ARQ_PORT>.*<\/ARQ_PORT>/<ARQ_PORT>${ARQ_PORT[$SIDE]}<\/ARQ_PORT>/" \
   -e "s/<FLRIG_IP_PORT>.*<\/FLRIG_IP_PORT>/FLRIG_IP_PORT>${FLRIG_PORT[$SIDE]}<\/FLRIG_IP_PORT>/" \
   -e "s/<XMLLOG_PORT>.*<\/XMLLOG_PORT>/XMLLOG_PORT>${XMLLOG_PORT[$SIDE]}<\/XMLLOG_PORT>/" \
   -e "s/<FSQLOWERCASE>.*<\/FSQLOWERCASE>/<FSQLOWERCASE>1<\/FSQLOWERCASE>/" \
   -e "s/<FSQSHOWMONITOR>.*<\/FSQSHOWMONITOR>/<FSQSHOWMONITOR>1<\/FSQSHOWMONITOR>/" \
   -e "s/<OPEN_FLMSG_PRINT>.*<\/OPEN_FLMSG_PRINT>/<OPEN_FLMSG_PRINT>0<\/OPEN_FLMSG_PRINT>/" \
   -e "s|<FLMSG_PATHNAME>.*</FLMSG_PATHNAME>|<FLMSG_PATHNAME>$FLMSG_STRING</FLMSG_PATHNAME>|" \
  	-e "s/<REVERSEAUDIO>.*<\/REVERSEAUDIO>/<REVERSEAUDIO>${REVERSEAUDIO[$SIDE]}<\/REVERSEAUDIO>/" \
   -e "s/<REVERSERXAUDIO>.*<\/REVERSERXAUDIO>/<REVERSERXAUDIO>${REVERSEAUDIO[$SIDE]}<\/REVERSERXAUDIO>/" \
   $HOME/.fldigi-$SIDE/fldigi_def.xml 
	echo >&2 "Done."
	
	# Flrig
	rm -rf $HOME/.flrig-$SIDE
	echo >&2 "Initializing Flrig $SIDE"
	flrig --debug-level 0 --config-dir $HOME/.flrig-$SIDE &
   PID_=$!
   sleep 2
   for WID in $(xdotool search --pid $PID_ 2>/dev/null | sort -r)
   do
   	xdotool windowclose $WID >/dev/null 2>&1
   	sleep 1
   done
   pkill -SIGTERM flrig
   sed -i -e "s/^xmlport:.*/xmlport:${FLRIG_PORT[$SIDE]}/" $HOME/.flrig-$SIDE/NONE.prefs
   echo "xmlport:${FLRIG_PORT[$SIDE]}" >> $HOME/.flrig-$SIDE/flrig.prefs
	echo >&2 "Done."
	
	# Flmsg
	echo >&2 "Initializing Flmsg $SIDE"
   flmsg --flmsg-dir $HOME/.nbems-$SIDE >/dev/null 2>&1 &
   PID_=$!
   sleep 2
   WID=$(xdotool search --pid $PID_ 2>/dev/null)
   xdotool windowclose $WID >/dev/null 2>&1
   sleep 1
   for WID in $(xdotool search --name "flmsg")
   do
      xdotool windowclose $WID >/dev/null 2>&1
   done
   WaitFor $HOME/.nbems-$SIDE/FLMSG.prefs || Die "$HOME/.nbems-$SIDE/FLMSG.prefs never created."
	pkill -SIGTERM flmsg
   sed -i -e "s/^xmlrpc_port:.*/xmlrpc_port:${XML_PORT[$SIDE]}/" $HOME/.nbems-$SIDE/FLMSG.prefs
	echo >&2 "Done."

	# Flamp
	echo >&2 "Initializing Flamp $SIDE"
   fldigi --config-dir $HOME/.fldigi-$SIDE --flmsg-dir $HOME/.nbems-$SIDE >/dev/null 2>&1 &
   sleep 5
   flamp --config-dir $HOME/.nbems-$SIDE --xmlrpc-server-port ${XML_PORT[$SIDE]} >/dev/null 2>&1 &
   PID_=$!
   sleep 1
   for WID in $(xdotool search --pid $PID_ | sort -r)
   do
	   xdotool windowclose $WID >/dev/null 2>&1
	   sleep 1
   done
   pkill -SIGTERM flamp
	pkill -SIGTERM fldigi
   WaitFor $HOME/.nbems-$SIDE/FLAMP/FLAMP.prefs || Die "$HOME/.nbems-$SIDE/FLAMP/FLAMP.prefs never created."
   sed -i -e "s/^xmlrpc_port:.*/xmlrpc_port:${XML_PORT[$SIDE]}/" \
   		-e "s/^socket_port:.*/xmlrpc_port:${ARQ_PORT[$SIDE]}/" \
   		$HOME/.nbems-$SIDE/FLAMP/FLAMP.prefs
	echo >&2 "Done."
	
	# Flarq
	echo >&2 "Initializing Flarq $SIDE"
   sudo sed -i -e "s/arq-server-port.*/arq-server-port ${ARQ_PORT[$SIDE]}/" \
   		/usr/local/share/applications/flarq-$SIDE.desktop \
   		/usr/local/share/applications/flarq-$SIDE.template
	echo >&2 "Done."
	
done

rm -f $HOME/DO_NOT_DELETE_THIS_FILE
echo >&2 "Initialization complete. Reboot now."

